// Built-in look library. A fresh install used to show no presets at all --
// the editor opened on a blank slate and you had to know what "gradient,
// speed 0.2" would look like. These ship with the app so the first move is
// always "pick a look you like", not "configure an effect".
//
// User-saved presets live in show.json and are shown alongside these.

import type { PresetSpec } from './show'

export const BUILTIN_PRESETS: PresetSpec[] = [
  {
    id: 'builtin-warm',
    name: 'Warm wash',
    target: 'both',
    effect: 'solid',
    params: { color: '#ff9d3d' },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-cold',
    name: 'Cold wash',
    target: 'both',
    effect: 'solid',
    params: { color: '#9fd4ff' },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-red',
    name: 'Deep red',
    target: 'both',
    effect: 'solid',
    params: { color: '#ff1e2d' },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-magenta',
    name: 'Magenta',
    target: 'both',
    effect: 'solid',
    params: { color: '#ff2d9e' },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-sunset',
    name: 'Sunset',
    target: 'both',
    effect: 'gradient',
    params: { colorA: '#ff5a1f', colorB: '#ff2d78', speed: 0.12 },
    fadeIn: 1,
    fadeOut: 1,
  },
  {
    id: 'builtin-ocean',
    name: 'Ocean',
    target: 'both',
    effect: 'gradient',
    params: { colorA: '#0a5cff', colorB: '#00e0c6', speed: 0.2 },
    fadeIn: 1,
    fadeOut: 1,
  },
  {
    id: 'builtin-slow-wave',
    name: 'Slow wave',
    target: 'both',
    effect: 'wave',
    params: { color: '#ffb340', speed: 0.35, size: 2 },
    fadeIn: 1,
    fadeOut: 1,
  },
  {
    id: 'builtin-pulse',
    name: 'Pulse',
    target: 'both',
    effect: 'wave',
    params: { color: '#c9e4ff', speed: 1.6, size: 1 },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-runner',
    name: 'Runner',
    target: 'both',
    effect: 'chase',
    params: { color: '#b4dcff', speed: 1, count: 2 },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-chase-four',
    name: 'Four runners',
    target: 'both',
    effect: 'chase',
    params: { color: '#ffd166', speed: 1.8, count: 4 },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-sparkle',
    name: 'Sparkle',
    target: 'both',
    effect: 'sparkle',
    params: { color: '#ffffff', density: 0.25, speed: 5 },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-fireflies',
    name: 'Fireflies',
    target: 'both',
    effect: 'sparkle',
    params: { color: '#ffcf6b', density: 0.12, speed: 2 },
    fadeIn: 1,
    fadeOut: 1,
  },
  {
    id: 'builtin-amber-deep',
    name: 'Amber',
    target: 'both',
    effect: 'solid',
    params: { color: '#ff7a00' },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-uv',
    name: 'Deep violet',
    target: 'both',
    effect: 'solid',
    params: { color: '#6a2dff' },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-lime',
    name: 'Acid green',
    target: 'both',
    effect: 'solid',
    params: { color: '#8bff2d' },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-white',
    name: 'Full white',
    target: 'both',
    effect: 'solid',
    params: { color: '#ffffff' },
    fadeIn: 0.3,
    fadeOut: 0.3,
  },
  {
    id: 'builtin-fire',
    name: 'Fire',
    target: 'both',
    effect: 'gradient',
    params: { colorA: '#ff2d00', colorB: '#ffc400', speed: 0.45 },
    fadeIn: 0.8,
    fadeOut: 0.8,
  },
  {
    id: 'builtin-ice',
    name: 'Ice',
    target: 'both',
    effect: 'gradient',
    params: { colorA: '#7ad7ff', colorB: '#ffffff', speed: 0.1 },
    fadeIn: 1,
    fadeOut: 1,
  },
  {
    id: 'builtin-neon',
    name: 'Neon',
    target: 'both',
    effect: 'gradient',
    params: { colorA: '#ff00d4', colorB: '#00ffe0', speed: 0.6 },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-sunset-reverse',
    name: 'Sunset reverse',
    target: 'both',
    effect: 'gradient',
    params: { colorA: '#ff5a1f', colorB: '#ff2d78', speed: -0.35 },
    fadeIn: 1,
    fadeOut: 1,
  },
  {
    id: 'builtin-breathe',
    name: 'Breathe',
    target: 'both',
    effect: 'wave',
    params: { color: '#ffd9a0', speed: 0.18, size: 0.5 },
    fadeIn: 1.5,
    fadeOut: 1.5,
  },
  {
    id: 'builtin-ripple',
    name: 'Ripple',
    target: 'both',
    effect: 'wave',
    params: { color: '#4fd2ff', speed: 1, size: 6 },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-wave-reverse',
    name: 'Wave reverse',
    target: 'both',
    effect: 'wave',
    params: { color: '#ffb340', speed: -0.35, size: 2 },
    fadeIn: 1,
    fadeOut: 1,
  },
  {
    id: 'builtin-heartbeat',
    name: 'Heartbeat',
    target: 'both',
    effect: 'wave',
    params: { color: '#ff2d4a', speed: 2.4, size: 0.5 },
    fadeIn: 0.3,
    fadeOut: 0.3,
  },
  {
    id: 'builtin-single-runner',
    name: 'Single runner',
    target: 'both',
    effect: 'chase',
    params: { color: '#ffffff', speed: 1.4, count: 1 },
    fadeIn: 0.3,
    fadeOut: 0.3,
  },
  {
    id: 'builtin-runner-reverse',
    name: 'Runner reverse',
    target: 'both',
    effect: 'chase',
    params: { color: '#b4dcff', speed: -1, count: 2 },
    fadeIn: 0.5,
    fadeOut: 0.5,
  },
  {
    id: 'builtin-fast-chase',
    name: 'Fast chase',
    target: 'both',
    effect: 'chase',
    params: { color: '#ff2d9e', speed: 2.8, count: 3 },
    fadeIn: 0.3,
    fadeOut: 0.3,
  },
  {
    id: 'builtin-storm',
    name: 'Storm',
    target: 'both',
    effect: 'sparkle',
    params: { color: '#dbeaff', density: 0.55, speed: 10 },
    fadeIn: 0.2,
    fadeOut: 0.2,
  },
  {
    id: 'builtin-stars',
    name: 'Stars',
    target: 'both',
    effect: 'sparkle',
    params: { color: '#ffffff', density: 0.08, speed: 1.5 },
    fadeIn: 1.5,
    fadeOut: 1.5,
  },
  {
    id: 'builtin-embers',
    name: 'Embers',
    target: 'both',
    effect: 'sparkle',
    params: { color: '#ff6a1f', density: 0.2, speed: 3 },
    fadeIn: 1,
    fadeOut: 1,
  },
  {
    id: 'builtin-blackout',
    name: 'Blackout',
    target: 'both',
    effect: 'solid',
    params: { color: '#000000' },
    fadeIn: 0.4,
    fadeOut: 0.4,
  },
]

export function isBuiltinPreset(id: string): boolean {
  return id.startsWith('builtin-')
}
